---
title: "0. Installing Software"
author: "Nazarii Hrubiian"
date: "`r Sys.Date()`"
format: 
 html:
  code-tools: true
  self-contained: true
  theme:
    light: github
    dark: darkly
  toc: true
  highlight-style: github
  embed-resources: true
---

# Вступ

Windows Subsystem for Linux (WSL) дозволяє вам запускати дистрибутив Linux поруч із вашою операційною системою Windows. Цей документ надає покрокові інструкції для встановлення Ubuntu на WSL.

# Попередні вимоги

- Windows 10 версії 1903 або новішої, або Windows 11
- Адміністративні права на вашій машині

# Крок 1: Увімкнути WSL

1. Відкрийте **PowerShell** від імені адміністратора.
   
   Шукайте "PowerShell" в меню «Пуск», клацніть правою кнопкою миші та виберіть "Запустити від імені адміністратора".

2. Виконайте наступну команду для увімкнення WSL:

   ```powershell
   wsl --install
   ```
  Ця команда завантажить останню версію WSL і встановить всі необхідні компоненти.

# Крок 2: Перезавантажте комп'ютер
Після виконання команди вам потрібно буде перезавантажити комп'ютер, щоб зміни вступили в силу.


# Крок 3: Запустіть Ubuntu
Після встановлення ви можете запустити Ubuntu з меню «Пуск» або набравши ubuntu у PowerShell або командному рядку.

Під час першого запуску Ubuntu потрібно буде кілька хвилин для налаштування. Вам буде запропоновано створити обліковий запис користувача та пароль.

# Крок 4: Оновіть Ubuntu
Після встановлення Ubuntu корисно оновити списки пакетів, щоб переконатися, що у вас є останнє програмне забезпечення.


```bash
sudo apt update
sudo apt upgrade
```



Ви успішно встановили **Ubuntu** на Windows Subsystem for Linux (WSL)! Тепер ви можете використовувати **Ubuntu** разом із вашими Windows-додатками. 

Щоб дізнатися більше про розширені налаштування, розгляньте можливість ознайомлення з документацією WSL на вебсайті [Microsoft](https://learn.microsoft.com/en-us/windows/wsl/install).


# Встановлення Miniconda
```bash
#створення папки miniconda3
mkdir -p ~/miniconda3
#Завантаження останньої версії дистрибутиву
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
#Інсталяція дистрибутиву
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
#Видалення інсталятора
rm ~/miniconda3/miniconda.sh
```
Детальніше на [сайті](https://docs.anaconda.com/miniconda/)

# Встановлення Miniconda на MacOS
Інсталяцію дистрибутиву можна знайти на сайті розробників [conda.io](https://conda.io/projects/conda/en/latest/user-guide/install/macos.html)


   
   
